#!/usr/bin/env sh

# Reset
COLOR_OFF='\033[0m'       # Text Reset

# Background
ON_RED='\033[41m'         # Red
ON_YELLOW='\033[43m'      # Yellow
ON_GREEN='\033[42m'       # Green

# Bold High Intensity
BIGREEN='\033[1;92m'      # Green

# High Intensity backgrounds
ON_IRED='\033[0;101m'     # Red
ON_IYELLOW='\033[0;103m'  # Yellow

if [ ! -d "node_modules" ]; then
  yarn
fi

local_branch_name="$(git branch --show-current)"
valid_branch_regex="^(build|ci|docs|feat|fix|perf|refactor|revert|style|test)\/[a-zA-Z\-]+"
invalid_branch_regex="^(develop|main)$"

if [[ $local_branch_name =~ $invalid_branch_regex ]]; then
    echo ""
    echo "$ON_IYELLOW ⚠︎ WARNING ⚠︎ "
    echo "$COLOR_OFF"
    echo "You are trying to commit in a branch where you are not allowed to commit"
    echo "Please reconsider making this commit in a valid branch"
elif [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo ""
    echo "$ON_IRED ⚠︎ WARNING ⚠︎ "
    echo "$COLOR_OFF"
    echo "There is something wrong with your branch name."
    echo "Branch names in this project must adhere to this contract: $ON_GREEN build|ci|docs|feat|fix|perf|refactor|revert|style|test $ON_YELLOW / $ON_GREEN subject."
    echo "$ON_RED"
    echo "Your commit will be rejected."
    echo "$COLOR_OFF"
    echo "You should rename your branch to a valid name and try again."
    exit 1
else
    echo ""
    echo "$BIGREEN ✔︎ CONGRATS ✔︎ "
    echo "$COLOR_OFF"
    echo " Your branch name matches with our branch convention."
    echo "$COLOR_OFF"
fi

echo ""
echo "$BIGREEN Lets validate your code with PRETTIER before committing..."
echo "$COLOR_OFF"
echo ""
format_output=$(yarn run validate:format) && format_exit_status=$? || format_exit_status=$?

if ((format_exit_status == 0)); then # TRY
    echo ""
    echo "$BIGREEN ✔︎ CONGRATS ✔︎ "
    echo ""
    echo "$COLOR_OFF"
    echo "All files are formatted correctly."
    echo "$COLOR_OFF"
else # CATCH
    echo ""
    echo "$ON_RED ⚠︎ WARNING ⚠︎ "
    echo ""
    echo "$COLOR_OFF"
    echo "There is something wrong with your files"
    echo ""
    echo "$ON_YELLOW You need to fix this"
    echo "$COLOR_OFF"
    exit 1
fi

echo ""
echo "$BIGREEN Lets validate your code with STYLELINT before committing..."
echo "$COLOR_OFF"
echo ""
csslint_output=$(yarn run validate:css) && csslint_exit_status=$? || csslint_exit_status=$?

if ((csslint_exit_status == 0)); then # TRY
    echo ""
    echo "$BIGREEN ✔︎ CONGRATS ✔︎ "
    echo ""
    echo "$COLOR_OFF"
    echo "All files are linted correctly."
    echo "$COLOR_OFF"
else # CATCH
    echo ""
    echo "$ON_RED ⚠︎ WARNING ⚠︎ "
    echo ""
    echo "$COLOR_OFF"
    echo "There is something wrong with your files"
    echo "$ON_YELLOW You need to fix this"
    echo "$COLOR_OFF"
    exit 1
fi
